---
title: Primates
timezone: America/Vancouver
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: "/blog"
    type: posts
  values:
    layout: post
    comments: true
    social-share: true
- scope:
    path: ''
  values:
    layout: page
    show-avatar: true
description: Guides for developers
navbar-links:
  About Me: aboutme
  Resources:
  - H2GD - Collection: https://guide.devlup.fr/
avatar: "/img/monkey.png"
navbar-col: "#F5F5F5"
navbar-text-col: "#363636"
navbar-children-col: "#F5F5F5"
page-col: "#FFFFFF"
link-col: "#68826F"
hover-col: "#757575"
footer-col: "#F5F5F5"
footer-text-col: "#777777"
footer-link-col: "#404040"
author:
  name: Stanislas Girard
social-network-links:
  rss: true
  email: girard.stanislas@pm.me
  facebook: StanGirard
  github: StanGirard
  twitter: StanGirard
share-links-active:
  twitter: true
  facebook: true
  linkedin: false
url-pretty: Primates.dev
google_analytics: UA-129019066-7
disqus: h2gd
staticman:
  repository: 
  branch: master
  endpoint: 
  reCaptcha:
    siteKey: 
    secret: 
excerpt_length: 50
title-separator: "-"
date_format: "%B %-d, %Y"
markdown: kramdown
highlighter: rouge
permalink: "/:year-:month-:day-:title/"
paginate: 10
kramdown:
  input: GFM
link-tags: true
exclude:
- CHANGELOG.md
- CNAME
- Dockerfile
- Gemfile
- Gemfile.lock
- LICENSE
- README.md
- Vagrantfile
prose:
  rooturl: _posts
  media: img
  ignore:
  - 404.html
  - LICENSE
  - feed.xml
  - _config.yml
  - "/_layouts"
  - "/_includes"
  - "/css"
  - "/img"
  - "/js"
  metadata:
    _posts:
    - name: layout
      field:
        element: hidden
        value: post
    - name: title
      field:
        element: text
        label: Post title
        placeholder: Title
        alterable: true
    - name: subtitle
      field:
        element: textarea
        label: Subtitle
        placeholder: A description of your post.
        alterable: true
    - name: bigimg
      field:
        element: text
        label: Big Image
        help: Add a big image to your post. **/img/img.png**
        placeholder: 'Landscape Image '
        alterable: true
    - name: image
      field:
        element: text
        label: Image
        help: Add a thumbnail image to your post. **/img/img.png**
        placeholder: Thumbnail
        alterable: true
    - name: tags
      field:
        element: multiselect
        label: Tags of the article
        placeholder: Choose your tags
        alterable: true
        options:
        - name: Cloud
          value: Cloud
        - name: SEO
          value: SEO
    - name: date
      field:
        element: text
        label: Date
        help: Enter date of post.
        placeholder: yyyy-mm-dd
        alterable: true
    - name: published
      field:
        element: checkbox
        label: Publish
        help: Check to publish post, uncheck to hide.
plugins:
- jekyll-paginate
- jekyll-sitemap
- github-pages
