backend:
  name: github
  repo: StanGirard/Primates
  branch: master

publish_mode: editorial_workflow

media_folder: "img"

collections:
  - name: "Articles"
    label: "Articles"
    folder: "_posts"
    create: true
    editor:
      preview: false
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Subtitle", name: "subtitle", widget: "text"}
      - {label: "Categories", name: "categories", widget: "list"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Landscape Image", name: "bigimg", widget: "image", required: false}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Share Image", name: "share-img", widget: "image", required: false}
      - {label: "Author", name: "author", widget: "list"}
      - {label: "Date", name: "date", widget: "datetime", format: "YYYY-MM-DD HH:mm:ss"}
      - {label: "Article", name: "content", widget: "markdown"}
    