backend:
  name: github
  repo: StanGirard/Primates
  branch: master
  open_authoring: true

publish_mode: editorial_workflow

media_folder: "img"

collections:
  - name: "Articles"
    label: "Articles"
    folder: "_posts"
    create: true
    editor:
      preview: false
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    preview_path: "{{title}}"
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Subtitle", name: "subtitle", widget: "text"}
      - {label: "Categories", name: "categories", widget: "list"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Landscape Image", name: "bigimg", widget: "image", required: false}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Share Image", name: "share-img", widget: "image", required: false}
      - {
      label: 'Author',
      name: 'author',
      widget: 'relation',
      collection: 'authors',
      displayFields: [display_name],
      searchFields: [display_name],
      valueField: 'name',
      multiple: true,
    }
      - {label: "Date", name: "date", widget: "datetime", format: "YYYY-MM-DD"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: 'authors'
    label: 'Authors'
    folder: '_authors/'
    create: true
    editor:
      preview: false
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "page"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Subtitle", name: "subtitle", widget: "string"}
      - {label: "username", name: "name", widget: "string"}
      - {label: "Display Name", name: "display_name", widget: "string"}
      - {label: "Email", name: "email", widget: "string"}
      - {label: "Website", name: "web", widget: "string", required: true}
      - {label: "Css", name: "css", widget: "string", required: false}
      - { label: 'Position', name: 'position', widget: 'string' }
      - {label: "Body", name: "body", widget: "markdown"}
  