backend:
  name: github
  repo: StanGirard/Primates
  branch: master

publish_mode: editorial_workflow

media_folder: "img"

collections:
  - name: "Articles"
    label: "Articles"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Subtitle", name: "subtitle", widget: "text"}
      - {label: "Landscape Image", name: "bigimg", widget: "image"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Document", name: "content", widget: "markdown"}
    